name: Build and Push Docker Image
run-name: Build and Push ${{ github.ref_name }}

on:
  push:
    branches-ignore:
      - "master"

jobs:
  call-docker-build:
    uses: adamanteye/actions/.github/workflows/docker.yml@master
    with:
      name: ${{ github.ref_name }}
      owner: $ {{ github.repository_owner }}
