name: Build and Push Docker Image
run-name: Build and Push ${{ github.ref_name }}

on:
  push:
    branches-ignore:
      - "master"
    paths-ignore:
      - "README.md"

jobs:
  call-docker-build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["linux/amd64", "linux/arm64"]
    permissions:
      contents: read
      packages: write
    uses: adamanteye/actions/.github/workflows/docker.yml@master
    with:
      name: ${{ github.ref_name }}
      owner: ${{ github.repository_owner }}
      arch: ${{ matrix.arch }}
      label: ${{ github.ref_type != 'tag' && 'latest' || github.ref_name }}
